# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a3b5769b7dd7e16a9602bb04d4ce5f578be39053275d8db6aca760a13c94084cad63c17983667734dfec77fb87d119ac71a9a9042a76dc1f6b797e2816e4b17

test:
  secret_key_base: 5c785d5688b545324c50c2ac00d4f056adb7db06638b926627bdcf6cd00eac68404644f65cdb76ffc1350b3f418bf04eca8dfddebfb2787142faa13f6b556a8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
